
logging:
  level:
    root: INFO

spring:
  datasource:
    username: local
    password: local!@#
    url: jdbc:h2:mem:localDB
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format-sql: true
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: create
      naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      use-new-id-generator-mappings: false
    generate-ddl: false

  h2:
    console:
      enabled: true

